# -- 코드를 입력하세요
# WITH AVG_REVIEW AS(
#     SELECT 
#         REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
#     FROM
#         REST_REVIEW
    
#     GROUP BY REST_ID
# )

# SELECT 
#     A.REST_ID, 
#     A.REST_NAME, 
#     A.FOOD_TYPE, 
#     A.FAVORITES, 
#     A.ADDRESS, 
#     B.SCORE
    
# FROM REST_INFO A, AVG_REVIEW B
# WHERE
#     A.REST_ID = B.REST_ID AND
#     ADDRESS LIKE "서울%"
# ORDER BY SCORE DESC, FAVORITES ASC


# -- 코드를 입력하세요
SELECT REST_INFO.REST_ID , REST_INFO.REST_NAME , FOOD_TYPE,REST_INFO.FAVORITES , REST_INFO.ADDRESS,round(AVG(REST_REVIEW.REVIEW_SCORE),2) score
FROM REST_INFO
JOIN REST_REVIEW
ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY REST_INFO.REST_NAME
ORDER BY round(AVG(REST_REVIEW.REVIEW_SCORE),2) DESC, REST_INFO.FAVORITES DESC
