SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') date_of_birth
FROM MEMBER_PROFILE
WHERE (
    extract(month from DATE_OF_BIRTH) = 3 AND 
    GENDER = 'W' AND
    TLNO IS NOT NULL
) ORDER BY MEMBER_ID ASC